[project]
name = "planneto_bio_integration"
authors = [
    { name = "Administrator", email = "admin@example.com"}
]
description = "eSSL Biometric Integration for Planetto"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    # "frappe~=15.0.0" # Managed by bench
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.frappe-dependencies]
frappe = ">=15.0.0,<16.0.0"
hrms = ">=15.0.0,<16.0.0"

[tool.bench.dev-dependencies]

[tool.ruff]
line-length = 110
target-version = "py310"

[tool.ruff.lint]
select = [
    "F",
    "E",
    "W",
    "I",
    "UP",
    "B",
    "RUF",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "tab"
docstring-code-format = true
